### ISSUE TITLE
[DOCS]typo mistake

### ISSUE THREAD

**Issue by Vidya4sure** [shubhsharma19/web-dev-journey#49]
typo mistake in git document 
![image](https://github.com/shubhsharma19/web-development-journey/assets/123371804/35caf10e-1579-4c60-aa5a-6a4e8ceda72e)

correct name 
![image](https://github.com/shubhsharma19/web-development-journey/assets/123371804/35d29177-2354-4e04-9b3f-5e1747a0e312)

**Comment by shubhxg** [comment]
Thanks LGTM
